import sqlite3

data = [
    ("L00", "Staphylococcal scalded skin syndrome"),
    ("L01", "Impetigo"),
    ("L02", "Cutaneous abscess, furuncle and carbuncle"),
    ("L03", "Cellulitis and acute lymphangitis"),
    ("L04", "Acute lymphadenitis"),
    ("L05", "Pilonidal cyst and sinus"),
    ("L08", "Other local infections of skin and subcutaneous tissue"),
    ("L10", "Pemphigus"),
    ("L11", "Other acantholytic disorders"),
    ("L12", "Pemphigoid"),
    ("L13", "Other bullous disorders"),
    ("L14", "Bullous disorders in diseases classified elsewhere"),
    ("L20", "Atopic dermatitis"),
    ("L21", "Seborrhoeic dermatitis"),
    ("L22", "Diaper dermatitis"),
    ("L23", "Allergic contact dermatitis"),
    ("L24", "Irritant contact dermatitis"),
    ("L25", "Unspecified contact dermatitis"),
    ("L26", "Exfoliative dermatitis"),
    ("L27", "Dermatitis due to substances taken internally"),
    ("L28", "Lichen simplex chronicus and prurigo"),
    ("L29", "Pruritus"),
    ("L30", "Other and unspecified dermatitis"),
    ("L40", "Psoriasis"),
    ("L41", "Parapsoriasis"),
    ("L42", "Pityriasis rosea"),
    ("L43", "Lichen planus"),
    ("L44", "Other papulosquamous disorders"),
    ("L45", "Papulosquamous disorders in diseases classified elsewhere"),
    ("L49", "Exfoliation due to erythematous conditions according to extent of body surface involved"),
    ("L50", "Urticaria"),
    ("L51", "Erythema multiforme"),
    ("L52", "Erythema nodosum"),
    ("L53", "Other erythematous conditions"),
    ("L54", "Erythematous conditions in diseases classified elsewhere"),
    ("L55", "Sunburn"),
    ("L56", "Other acute skin changes due to ultraviolet radiation"),
    ("L57", "Skin changes due to chronic exposure to nonionizing radiation"),
    ("L58", "Radiodermatitis"),
    ("L59", "Other disorders of skin and subcutaneous tissue related to radiation"),
    ("L60", "Nail disorders"),
    ("L61", "Nail disorders in diseases classified elsewhere"),
    ("L62", "Nail disorders due to repeated trauma"),
    ("L63", "Alopecia areata"),
    ("L64", "Androgenic alopecia"),
    ("L65", "Other non-scarring hair loss"),
    ("L66", "Cicatricial alopecia [scarring hair loss]"),
    ("L67", "Hair color and hair shaft abnormalities"),
    ("L68", "Hypertrichosis"),
    ("L70", "Acne"),
    ("L71", "Rosacea"),
    ("L72", "Follicular cysts of skin and subcutaneous tissue"),
    ("L73", "Other follicular disorders"),
    ("L74", "Eccrine sweat disorders"),
    ("L75", "Apocrine sweat disorders"),
    ("L76", "Intraoperative and postprocedural complications of skin and subcutaneous tissue"),
    ("L80", "Vitiligo"),
    ("L81", "Other disorders of pigmentation"),
    ("L82", "Seborrhoeic keratosis"),
    ("L83", "Acanthosis nigricans"),
    ("L84", "Corns and callosities"),
    ("L85", "Other epidermal thickening"),
    ("L86", "Keratoderma in diseases classified elsewhere"),
    ("L87", "Transepidermal elimination disorders"),
    ("L88", "Pyoderma gangrenosum"),
    ("L89", "Pressure ulcer"),
    ("L90", "Atrophic disorders of skin"),
    ("L91", "Hypertrophic disorders of skin"),
    ("L92", "Granulomatous disorders of skin and subcutaneous tissue"),
    ("L93", "Lupus erythematosus"),
    ("L94", "Other localized connective tissue disorders"),
    ("L95", "Vasculitis limited to skin, not elsewhere classified"),
    ("L97", "Non-pressure chronic ulcer of lower limb, not elsewhere classified"),
    ("L98", "Other disorders of skin and subcutaneous tissue, not elsewhere classified"),
    ("L99", "Other disorders of skin and subcutaneous tissue in diseases classified elsewhere"),
    ("M00", "Pyogenic arthritis"),
    ("M01", "Direct infections of joint in infectious and parasitic diseases classified elsewhere"),
    ("M02", "Postinfective and reactive arthropathies"),
    ("M04", "Autoinflammatory syndromes"),
    ("M05", "Rheumatoid arthritis with rheumatoid factor"),
    ("M06", "Other rheumatoid arthritis"),
    ("M07", "Enteropathic arthropathies"),
    ("M08", "Juvenile arthritis"),
    ("M10", "Gout"),
    ("M11", "Other crystal arthropathies"),
    ("M12", "Other and unspecified arthropathy"),
    ("M13", "Other arthritis"),
    ("M14", "Arthropathies in other diseases classified elsewhere"),
    ("M1A", "Chronic gout"),
    ("M15", "Polyosteoarthritis"),
    ("M16", "Osteoarthritis of hip"),
    ("M17", "Osteoarthritis of knee"),
    ("M18", "Osteoarthritis of first carpometacarpal joint"),
    ("M19", "Other and unspecified osteoarthritis"),
    ("M20", "Acquired deformities of fingers and toes"),
    ("M21", "Other acquired deformities of limbs"),
    ("M22", "Disorders of patella"),
    ("M23", "Internal derangement of knee"),
    ("M24", "Other specific joint derangements"),
    ("M25", "Other joint disorders, not elsewhere classified"),
    ("M26", "Dentofacial anomalies [including malocclusion]"),
    ("M27", "Other diseases of jaws"),
    ("M30", "Polyarteritis nodosa and related conditions"),
    ("M31", "Other necrotizing vasculopathies"),
    ("M32", "Systemic lupus erythematosus (SLE)"),
    ("M33", "Dermatomyositis"),
    ("M34", "Systemic sclerosis [scleroderma]"),
    ("M35", "Other systemic involvement of connective tissue"),
    ("M36", "Systemic disorders of connective tissue in diseases classified elsewhere")
]

conn = sqlite3.connect("db.sqlite3")
cursor = conn.cursor()

for code, desc in data:
    cursor.execute("INSERT INTO diagnosis (code, description) VALUES (?, ?)", (code, desc))

conn.commit()
conn.close()